### ISSUE TITLE
Re-name this repo

### ISSUE THREAD

**Issue by pcarney8** [rht-labs/open-management-portal-frontend#1]
We should use good practices in naming our repos, otherwise no one will know what they are

**Comment by InfoSec812** [comment]
+1

**Comment by jacobsee** [comment]
@oybed @mcanoy Getting back to this. I would like to expand this out to `open-management-portal-frontend` so that it's clearer and matches the backend repo's name. Thoughts?

**Comment by oybed** [comment]
@jacobsee done
